# Generated by Django 3.1.4 on 2020-12-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seguros',
            fields=[
                ('seguro_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=8)),
                ('color', models.CharField(max_length=7)),
                ('prima_minima', models.FloatField()),
            ],
        ),
    ]
